/* usbconfig.h - V-USB configuration for the JJ4x4 USB-MIDI controller
 *
 * Target: ATmega32A @ 12 MHz crystal (ps2avrGB-style board).
 * USB D+ on PD2 (INT0), D- on PD3.
 *
 * Derived from the V-USB usbconfig prototype and the V-USB MIDI example.
 * V-USB is (c) OBJECTIVE DEVELOPMENT Software GmbH - GNU GPL v2
 * (see usbdrv/License.txt).
 *
 * This file MUST be named "usbconfig.h" and be on the include path: the
 * V-USB driver (usbdrv.h) includes it by that exact name.
 */
#ifndef __usbconfig_h_included__
#define __usbconfig_h_included__

#include <avr/io.h>     /* for the INT0 register names used further down */

/* ---------------------------- Hardware Config ---------------------------- */
/* D+ must be wired to the INT0 pin. On the ATmega32 INT0 is PD2. */
#define USB_CFG_IOPORTNAME      D
#define USB_CFG_DMINUS_BIT      3        /* PD3 */
#define USB_CFG_DPLUS_BIT       2        /* PD2 = INT0 */

#define USB_CFG_CLOCK_KHZ       (F_CPU/1000)   /* 12000 kHz - needs a crystal */
#define USB_CFG_CHECK_CRC       0

/* --------------------------- Functional Range ---------------------------- */
#define USB_CFG_HAVE_INTRIN_ENDPOINT    1   /* interrupt-IN endpoint 1 (MIDI) */
#define USB_CFG_HAVE_INTRIN_ENDPOINT3   0   /* only one endpoint needed       */
#define USB_CFG_EP3_NUMBER              3
#define USB_CFG_IMPLEMENT_HALT          0
#define USB_CFG_SUPPRESS_INTR_CODE      0
#define USB_CFG_INTR_POLL_INTERVAL      10
#define USB_CFG_IS_SELF_POWERED         0
#define USB_CFG_MAX_BUS_POWER           100
#define USB_CFG_IMPLEMENT_FN_WRITE      1
#define USB_CFG_IMPLEMENT_FN_READ       1
#define USB_CFG_IMPLEMENT_FN_WRITEOUT   1
#define USB_CFG_HAVE_FLOWCONTROL        0
#define USB_CFG_DRIVER_FLASH_PAGE       0
#define USB_CFG_LONG_TRANSFERS          0
#define USB_COUNT_SOF                   0
#define USB_CFG_CHECK_DATA_TOGGLING     0
#define USB_CFG_HAVE_MEASURE_FRAME_LENGTH   0
#define USB_USE_FAST_CRC                0

/* -------------------------- Device Description --------------------------- */
/* obdev's shared VID/PID pair for class-compliant USB-MIDI devices.
 * Free to use per usbdrv/USB-IDs-for-free.txt: the device must be a
 * MIDI-class device (it is) and carry a vendor/product name (set below). */
#define USB_CFG_VENDOR_ID       0xc0, 0x16     /* 0x16c0 */
#define USB_CFG_DEVICE_ID       0xe4, 0x05     /* 0x05e4 - shared MIDI PID */
#define USB_CFG_DEVICE_VERSION  0x00, 0x01

#define USB_CFG_VENDOR_NAME     'J','J','4','x','4'
#define USB_CFG_VENDOR_NAME_LEN 5
#define USB_CFG_DEVICE_NAME     'J','J','4','x','4',' ','M','I','D','I'
#define USB_CFG_DEVICE_NAME_LEN 10

#define USB_CFG_DEVICE_CLASS        0          /* defined at interface level */
#define USB_CFG_DEVICE_SUBCLASS     0
#define USB_CFG_INTERFACE_CLASS     0x01       /* AUDIO            */
#define USB_CFG_INTERFACE_SUBCLASS  0x03       /* MIDI Streaming   */
#define USB_CFG_INTERFACE_PROTOCOL  0x00
#define USB_CFG_HID_REPORT_DESCRIPTOR_LENGTH 0

/* ------------------- Fine Control over USB Descriptors ------------------- */
/* The device and configuration descriptors are MIDI-class specific, so we
 * supply them ourselves at runtime via usbFunctionDescriptor() (midi.c).
 * String descriptors are still generated by V-USB from the names above. */
#define USB_CFG_DESCR_PROPS_DEVICE                  USB_PROP_IS_DYNAMIC
#define USB_CFG_DESCR_PROPS_CONFIGURATION           USB_PROP_IS_DYNAMIC
#define USB_CFG_DESCR_PROPS_STRINGS                 0
#define USB_CFG_DESCR_PROPS_STRING_0                0
#define USB_CFG_DESCR_PROPS_STRING_VENDOR           0
#define USB_CFG_DESCR_PROPS_STRING_PRODUCT          0
#define USB_CFG_DESCR_PROPS_STRING_SERIAL_NUMBER    0
#define USB_CFG_DESCR_PROPS_HID                     0
#define USB_CFG_DESCR_PROPS_HID_REPORT              0
#define USB_CFG_DESCR_PROPS_UNKNOWN                 0

/* ----------------------- MCU interrupt description ----------------------- */
/* External interrupt INT0 on the ATmega32 (D+ pin). Defined explicitly so
 * the driver does not have to guess the register layout. */
#define USB_INTR_CFG            MCUCR
#define USB_INTR_CFG_SET        ((1 << ISC00) | (1 << ISC01))  /* rising edge */
#define USB_INTR_CFG_CLR        0
#define USB_INTR_ENABLE         GICR
#define USB_INTR_ENABLE_BIT     INT0
#define USB_INTR_PENDING        GIFR
#define USB_INTR_PENDING_BIT    INTF0
#define USB_INTR_VECTOR         INT0_vect

#endif /* __usbconfig_h_included__ */
